services:
  postgres:
    image: postgres:16
    container_name: setis-postgres
    environment:
      POSTGRES_DB: setis_db
      POSTGRES_USER: setis
      POSTGRES_PASSWORD: setis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
